### ISSUE TITLE
Video not working

### ISSUE THREAD

**Issue by jcgts** [sourcey/symple-client#2]
When attempting to video chat with someone, an error occurs and says that there should be three arguments instead of two. Unusable except for text chat the way it is.

**Comment by auscaster** [comment]
Hello, this issue was related to the online demo at http://symple.sourcey.com, not the symple client itself. The demo code has been updated and is working properly now. Please check the demo again, of you can get the full demo source code from https://github.com/sourcey/symple-client-webrtc-demo. Please close this issue when you're ready.
